export enum AgentType {
  HR_ASSISTANT = 'HR_ASSISTANT',
  LEAVE_AGENT = 'LEAVE_AGENT',
  CAREER_AGENT = 'CAREER_AGENT',
  LINGUISTIC_AGENT = 'LINGUISTIC_AGENT',
  ANALYTICS_AGENT = 'ANALYTICS_AGENT',
  ENGAGEMENT_AGENT = 'ENGAGEMENT_AGENT',
  ONBOARDING_COMPANION = 'ONBOARDING_COMPANION',
}
