// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/signin-variants/CenteredMinimal.tsx": () => import("../components/mockups/signin-variants/CenteredMinimal.tsx"),
  "./components/mockups/signin-variants/FullDarkGlass.tsx": () => import("../components/mockups/signin-variants/FullDarkGlass.tsx"),
  "./components/mockups/signin-variants/SplitDark.tsx": () => import("../components/mockups/signin-variants/SplitDark.tsx")
};
