export enum AiAgentRunStatus {
  PENDING = 'PENDING',
  RUNNING = 'RUNNING',
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
  DEGRADED = 'DEGRADED',
  PARTIAL = 'PARTIAL',
  ESCALATED = 'ESCALATED',
  REFUSED = 'REFUSED',
  OUT_OF_SCOPE = 'OUT_OF_SCOPE',
}
