export enum DashboardMetricKey {
  EMPLOYEES_EXITS               = 'EMPLOYEES_EXITS',
  EMPLOYEES_ATTRITION_RATE      = 'EMPLOYEES_ATTRITION_RATE',
  EMPLOYEES_PROBATION           = 'EMPLOYEES_PROBATION',
  LEAVE_PENDING_APPROVALS       = 'LEAVE_PENDING_APPROVALS',
  PROMOTIONS_PENDING_REQUESTS   = 'PROMOTIONS_PENDING_REQUESTS',
}
