export enum ExitSurveyQuestionKey {
  REASON_FOR_LEAVING = 'REASON_FOR_LEAVING',
  MANAGER_RATING = 'MANAGER_RATING',
  TEAM_CULTURE_RATING = 'TEAM_CULTURE_RATING',
  GROWTH_OPPORTUNITY_RATING = 'GROWTH_OPPORTUNITY_RATING',
  WOULD_RECOMMEND_COMPANY = 'WOULD_RECOMMEND_COMPANY',
  OPEN_FEEDBACK = 'OPEN_FEEDBACK',
}
