export enum FeedbackType {
  EVENT_FEEDBACK = 'EVENT_FEEDBACK',
  ANNOUNCEMENT_FEEDBACK = 'ANNOUNCEMENT_FEEDBACK',
  GENERAL_FEEDBACK = 'GENERAL_FEEDBACK',
  MANAGER_FEEDBACK = 'MANAGER_FEEDBACK',
  PEER_FEEDBACK = 'PEER_FEEDBACK',
}
