export enum NotificationEventType {
  REQUEST_SUBMITTED = 'REQUEST_SUBMITTED',
  REQUEST_APPROVED = 'REQUEST_APPROVED',
  REQUEST_REJECTED = 'REQUEST_REJECTED',
  REQUEST_CANCELLED = 'REQUEST_CANCELLED',
  DECISION_PENDING = 'DECISION_PENDING',
  RESOLVED = 'RESOLVED',
  INFO = 'INFO',
}
