export enum NotificationCategory {
  LEAVE = 'LEAVE',
  PROMOTION = 'PROMOTION',
  SKILL = 'SKILL',
  PERFORMANCE = 'PERFORMANCE',
  PROBATION = 'PROBATION',
  CONTRACT_AMENDMENT = 'CONTRACT_AMENDMENT',
  COMPLAINT = 'COMPLAINT',
  ENGAGEMENT = 'ENGAGEMENT',
  EXIT_SURVEY = 'EXIT_SURVEY',
  OKR = 'OKR',
  SYSTEM = 'SYSTEM',
}
