export enum PerformanceRating {
  UNACCEPTABLE = 'UNACCEPTABLE',
  NEEDS_IMPROVEMENT = 'NEEDS_IMPROVEMENT',
  MEETS_EXPECTATIONS = 'MEETS_EXPECTATIONS',
  EXCEEDS_EXPECTATIONS = 'EXCEEDS_EXPECTATIONS',
  ABOVE_AND_BEYOND = 'ABOVE_AND_BEYOND',
}
