export enum PerformanceReviewAuditAction {
  CYCLE_CREATED = 'CYCLE_CREATED',
  ASSIGNED = 'ASSIGNED',
  SELF_SUBMITTED = 'SELF_SUBMITTED',
  MANAGER_COMPLETED = 'MANAGER_COMPLETED',
  REVIEWER_REASSIGNED = 'REVIEWER_REASSIGNED',
  REOPENED = 'REOPENED',
  CLOSED = 'CLOSED',
  CANCELLED = 'CANCELLED',
  SALARY_FOLLOW_UP_RECORDED = 'SALARY_FOLLOW_UP_RECORDED',
}
