export enum ReviewStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  SUBMITTED = 'SUBMITTED',
  COMPLETED = 'COMPLETED',
  REOPENED = 'REOPENED',
  CLOSED = 'CLOSED',
  CANCELLED = 'CANCELLED',
}
