import type { TourStep } from '@/components/guided-tour/types';
import { SLACK_APP_NAME, TELEGRAM_BOT_HANDLE } from '@/lib/channels/link-channel-copy';

/**
 * WHY the query string: the Linked Channels steps need the profile page to
 * open on that tab, and EmployeeProfile reads its active tab from `?tab=`.
 */
const LINKED_CHANNELS_ROUTE = '/profile?tab=channels';

export const ALL_TOUR_STEPS: readonly TourStep[] = [
  {
    id: 'home-nav',
    target: '[data-tour="home-nav"]',
    title: 'Home',
    description: 'Your daily dashboard — pending actions, recent activity, and quick links tailored to your role. Start every morning here.',
    placement: 'right',
    route: '/home',
    tiers: ['hr_admin', 'dept_manager', 'team_lead', 'employee'],
  },
  {
    id: 'profile-nav',
    target: '[data-tour="profile-nav"]',
    title: 'My Profile',
    description: 'View and update your personal info, contact details, and professional summary. Other modules like OKRs and performance link back to this.',
    placement: 'right',
    route: '/home',
    tiers: ['hr_admin', 'dept_manager', 'team_lead', 'employee'],
  },
  {
    id: 'leaves-nav',
    target: '[data-tour="leaves-nav"]',
    title: 'Leaves',
    description: 'Submit and track your leave requests, check remaining balances per leave type, and view your full request history.',
    placement: 'right',
    route: '/home',
    tiers: ['hr_admin', 'dept_manager', 'team_lead', 'employee'],
  },
  {
    id: 'org-chart-nav',
    target: '[data-tour="org-chart-nav"]',
    title: 'Org Chart',
    description: 'Explore the company structure — departments, teams, and reporting lines — in an interactive tree. Navigate to any employee profile directly.',
    placement: 'right',
    route: '/home',
    tiers: ['hr_admin', 'dept_manager', 'team_lead', 'employee'],
  },
  {
    id: 'performance-nav',
    target: '[data-tour="performance-nav"]',
    title: 'Performance Reviews',
    description: 'Complete self-assessments and view manager feedback across active review cycles. Track your ratings over time.',
    placement: 'right',
    route: '/home',
    tiers: ['hr_admin', 'dept_manager', 'team_lead', 'employee'],
  },
  {
    id: 'okrs-nav',
    target: '[data-tour="okrs-nav"]',
    title: 'OKRs',
    description: 'Your single hub for Objectives & Key Results — track personal OKRs, view cycle-wide progress, and manage cycles and check-ins, all in one place.',
    placement: 'right',
    route: '/home',
    tiers: ['hr_admin', 'dept_manager', 'team_lead', 'employee'],
  },
  {
    id: 'dashboard-nav',
    target: '[data-tour="dashboard-nav"]',
    title: 'Analytics Dashboard',
    description: 'A Power BI–style hub with real-time KPIs: headcount trends, payroll summaries, leave patterns, and engagement scores. Toggle chart types per panel.',
    placement: 'right',
    route: '/home',
    tiers: ['hr_admin', 'dept_manager', 'team_lead'],
  },
  {
    id: 'simulation-nav',
    target: '[data-tour="simulation-nav"]',
    title: 'Simulation',
    description: 'Model workforce changes before committing — propose promotions, transfers, or restructuring. The AI Agent analyses cost and skills impact.',
    placement: 'right',
    route: '/home',
    tiers: ['hr_admin', 'dept_manager', 'team_lead'],
  },
  {
    id: 'employees-nav',
    target: '[data-tour="employees-nav"]',
    title: 'Employees',
    description: 'The central employee registry — create employees, update details, manage role assignments, track salary history, and view skills profiles.',
    placement: 'right',
    route: '/home',
    tiers: ['hr_admin'],
  },
  {
    id: 'leave-mgmt-nav',
    target: '[data-tour="leave-mgmt-nav"]',
    title: 'Leave Management',
    description: 'Review and approve or reject pending leave requests. Configure leave types, accrual rules, carry-over policies, and view the full team calendar.',
    placement: 'right',
    route: '/home',
    tiers: ['hr_admin'],
  },
  {
    id: 'positions-nav',
    target: '[data-tour="positions-nav"]',
    title: 'Positions',
    description: 'Define and maintain the job position catalog. Each position carries required skills and salary bands — powering skills-gap analysis and the AI Career Agent.',
    placement: 'right',
    route: '/home',
    tiers: ['hr_admin'],
  },
  {
    id: 'notifications-bell',
    target: '[data-tour="notifications-bell"]',
    title: 'Notifications',
    description: 'Stay updated on leave approvals, review requests, OKR check-in reminders, and other important events — all in one inbox.',
    placement: 'bottom',
    tiers: ['hr_admin', 'dept_manager', 'team_lead', 'employee'],
  },
  {
    id: 'dark-mode-toggle',
    target: '[data-tour="dark-mode-toggle"]',
    title: 'Dark Mode',
    description: "Prefer working in the dark? Toggle between light and dark themes anytime from the sidebar footer. Your preference is saved automatically.",
    placement: 'right',
    tiers: ['hr_admin', 'dept_manager', 'team_lead', 'employee'],
  },
  {
    id: 'linked-channels-tab',
    target: '[data-tour="linked-channels-tab"]',
    title: 'Linked Channels',
    description: 'Sentient answers in Slack and Telegram too. Link your account once from this tab on your profile and you can check a balance or book leave without opening the app.',
    placement: 'bottom',
    route: LINKED_CHANNELS_ROUTE,
    tiers: ['hr_admin', 'dept_manager', 'team_lead', 'employee'],
  },
  {
    id: 'linked-channel-telegram',
    target: '[data-tour="linked-channel-telegram"]',
    title: 'Get your Telegram code',
    description: `Press Connect and Sentient issues a single-use 6-digit code. Open Telegram, message ${TELEGRAM_BOT_HANDLE}, and send it "/link" followed by that code — the dialog spells out the exact command and has a copy button.`,
    placement: 'right',
    route: LINKED_CHANNELS_ROUTE,
    tiers: ['hr_admin', 'dept_manager', 'team_lead', 'employee'],
  },
  {
    id: 'linked-channel-slack',
    target: '[data-tour="linked-channel-slack"]',
    title: 'Get your Slack code',
    description: `Same for Slack: press Connect, then direct-message the ${SLACK_APP_NAME} app "link" and the code — with no leading slash, which Slack would swallow as a slash command. Codes are short-lived, so generate a fresh one here if yours expires before you send it.`,
    placement: 'right',
    route: LINKED_CHANNELS_ROUTE,
    tiers: ['hr_admin', 'dept_manager', 'team_lead', 'employee'],
  },
] as const;
